# Generated by Django 3.2.5 on 2021-08-10 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('auction', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('auction_price', models.IntegerField()),
                ('commission_price', models.IntegerField(blank=True, null=True)),
                ('swift_price', models.IntegerField(blank=True, null=True)),
                ('distance_to_port', models.IntegerField()),
                ('delivery_land_price', models.IntegerField(blank=True, null=True)),
                ('delivery_sea_price', models.IntegerField()),
                ('delivery_all_price', models.IntegerField(blank=True, null=True)),
                ('customs_clearance_price', models.IntegerField(blank=True, null=True)),
                ('broker_forwarding_price', models.IntegerField(default=850)),
                ('certification_price', models.IntegerField(default=250)),
                ('company_services_price', models.IntegerField(default=400)),
                ('registration_price', models.IntegerField(blank=True, null=True)),
                ('end_price', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
